name: Build Minecraft Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: macromod-template-1.21.11
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Mod
          path: macromod-template-1.21.11/build/libs/*.jar
